version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      args:
        RUBY_VERSION: '3.0.1'
        BUNDLER_VERSION: '2.2'
    stdin_open: true
    tty: true
    volumes:
      - ./api:/home/dockeruser/project/api
      - bundle_gems:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development

volumes:
  bundle_gems:
    external: true
